### ISSUE TITLE
Conversion button not working after entering a valid YouTube URL

### ISSUE THREAD

**Issue by HritvikBhatia** [HritvikBhatia/yt-downloder#1]
### Description
When I click the "Convert" button after entering a valid YouTube URL, nothing happens. I expected the video to start converting, but no progress is shown, and no file is downloaded.

### Steps to Reproduce
1. Open the application in the browser.
2. Select "Video" from the dropdown menu.
3. Paste a valid YouTube URL (e.g., https://youtube.com/watch?v=example).
4. Click "Convert".

### Expected Behavior
The application should start converting the video and download the file.

### Actual Behavior
Nothing happens after clicking the "Convert" button.

**Comment by BaltiBerre** [comment]
I can pick this up, just let me know.

**Comment by HritvikBhatia** [comment]
@BaltiBerre Thanks so much for offering to help! Yes, please go ahead and work on solving this issue.

**Comment by BaltiBerre** [comment]
I fixed it!!!

**Comment by HritvikBhatia** [comment]
Could you send a pull request or share the code so I can review and merge it into the project?

**Comment by BaltiBerre** [comment]
Ok I just submitted my pull request, let me know if it works.

**Comment by BaltiBerre** [comment]
Did it work or not?
